name: build
on: [push, pull_request, release]
jobs:
  xcode-build:
    name: Xcode Build
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Build Jyutping
        run: set -o pipefail && xcodebuild clean build -project Jyutping/Jyutping.xcodeproj -scheme Jyutping -configuration Debug -destination "platform=iOS Simulator,name=iPhone 13" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
